apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
type: Opaque
data:
  apiKey: {{ .Values.datadogApiKeyBase64 }}
  appKey: {{ .Values.datadogAppKeyBase64 }}
  datadogSite: ZGF0YWRvZ2hxLmNvbQ==

