replicaCount: 1

service:
  targetPort: 8080

pod:
  resources:
    requests:
      memory: 256Mi
      cpu: 50m
    limits:
      memory: 512Mi
      cpu: 250m

hpa:
  enabled: true
  minReplicaCount: 1
  maxReplicaCount: 6
  fallback:
    failureThreshold: 3
    replicas: 4
  memoryThreshold: '5734000000'

configMap:
  springProfilesActive: production