name: 2- CI/CD Pipeline

on:
    push:
        branches: ['main', 'stage', 'dev']
    pull_request:
        branches: ['main', 'stage', 'dev']
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    build-and-publish:
      runs-on: ubuntu-latest
      environment: ${{ 
          github.ref_name == 'main' && 'prod' || 
          github.ref_name == 'stage' && 'stage' || 
          github.ref_name == 'dev' && 'dev'
          }}
      env:
          IMAGE_REPO: "${{ github.repository }}/${{ github.ref_name }}"
          URI_ECR: "${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com"
      steps:
        - uses: actions/checkout@v2

        - name: Build image using Buildpacks
          uses: bigloupe/buildpacks-action@master
          with:
            image: my-app-image
            path: ./
            builder: paketobuildpacks/builder:base
            tag: latest
    
            
