name: 3- CI/CD Pipeline

on:
    push:
        branches: ['main', 'stage', 'dev']
    pull_request:
        branches: ['main', 'stage', 'dev']
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: ${{ 
            github.ref_name == 'main' && 'prod' || 
            github.ref_name == 'stage' && 'stage' || 
            github.ref_name == 'dev' && 'dev'
            }}
        steps:
            - uses: actions/checkout@v4

            - name: Checkout helm-charts repository
              uses: actions/checkout@v4
              with:
                repository: org-sam/helm-charts
                path: helm-charts
   


            
