name: CI/CD Pipeline

on:
    push:
        branches: ['main', 'stage', 'dev']
    pull_request:
        branches: ['main', 'stage', 'dev']

env:
    artifact-name: build-artifact

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: public.ecr.aws/docker/library/gradle:7.3.3-jdk17-alpine
        steps:
            - uses: actions/checkout@v4
            - name: Build project
              run: |
                ./gradlew --version
                ./gradlew assemble --info
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: ${{ env.artifact-name }}
                path: ./build
                retention-days: 1
            - name: Listagem de arquivos
              run: |
                echo "pwd" && pwd
                echo "ls -la" && ls -la
                echo "ls -la ./build" && ls -la ./build

    publish:
        needs: [build]
        runs-on: ubuntu-latest
        if: github.ref_name == 'main' || github.ref_name == 'stage' || github.ref_name == 'dev'
        environment: ${{ 
            github.ref_name == 'main' && 'prod' || 
            github.ref_name == 'stage' && 'stage' || 
            github.ref_name == 'dev' && 'dev'
            }}
        steps:
            - uses: actions/checkout@v4
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                name: ${{ env.artifact-name }}
                path: ./build
            - name: Listagem de arquivos
              run: |
                echo "pwd" && pwd
                echo "ls -la" && ls -la
                echo "ls -la ./build" && ls -la ./build
            - uses: kciter/aws-ecr-action@v3
              with:
                access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                account_id: ${{ secrets.AWS_ACCOUNT_ID }}
                repo: org-sam/repo
                region: us-east-1
                tags: latest,${{ github.sha }}
                create_repo: true
                image_scanning_configuration: false
